language: java
# use Java 8
jdk:
- openjdk8

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false
install: true
script: ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -DrepoToken=2ws33DK94QibZDDcHAUtKeVnFJDlB1AD7
# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2